
export default {
    "Quản lí từ điển": "Dictionary Maganement",
    "Ngôn ngữ": "Language",
    "ĐĂNG NHẬP": "Login",
    "Quản lí chủ đề": "Topic Management",
    "TÀI KHOẢN": " USER",
    "ĐĂNG XUẤT": 'LOGOUT',
    "Cài đặt": " Settings",
    "Thêm mới": "Add New ",
    "Lưu": "Save",
    "Trở về": "Back",
    "Danh sách từ điển": "List of Dictionaries",
    "Tìm kiếm": "Search",
    "Danh sách yêu thích": "Favorite List",
    "Lịch sử tìm kiếm": "Search History",
    "Danh sách Chủ đề": "Topic List",
    "Tên chủ đề": "Topic Name",
    "Dịch nghĩa": "Translate",
    "Chủ đề": " Topic",
    "Từ vựng": "Vocabulary",
    "Mô tả": "Description",
    "Phát âm": "Pronunciation",
    "Yêu thích": "Favorite words",
    "Lịch sử tra từ": "Search History",
    "Thời gian": "Time",
    "Bật nhắc nhở từ vựng": "On/Off (Remind Vocabulary)",
    "Số từ/Ngày": "Number of words / day",
    "Thời gian nhắc bắt đầu": "The reminder time start",
    "Kết thúc": "End",
    "Chọn từ nhắc nhở": " Select Words Reminder",
    "Lịch sử": "History",
    "ĐĂNG KÍ":"Register",
    "Đăng kí":"Register",
    "Đăng nhập":"Login",
    "Thêm thành công vào mục yêu thích": "Added to favorite successfully",
    "Xóa thành công ra khỏi mục yêu thích" :"Removed from favorites successfully",
    "Lưu thành công":"Save successfully",
    "Lưu thất bại":"Save failed",
    "Đăng kí thành công": "Register successfully",
    "Đăng kí thất bại" : "Register failed",
    "Vui lòng chọn mục nhắc nhở" :"Please select a reminder",
    "Bạn chưa chọn danh sách nhắc nhở":"You have not selected the reminder list",
    "Đăng nhập thành công": "Login successfully",
    "Đăng nhập thất bại" : "Login failed",
    "STT" :"ID",
    "Số dòng":"Number of lines",
    "Số từ" :"Number of words",
    "Danh sách các từ đã chọn":"List of selected words",
    "Lịch sử":"History"
 
    
 
}
